### ISSUE TITLE
点击退出登录网页就崩溃了

### ISSUE THREAD

**Issue by haorenew** [lyj0309/pan#1]
点击退出登录网页就崩溃了，我用的MemFire Cloud的postgre数据库
这是我的配置文件
[System]
Mode = master
Listen = :5000

[Database]
; 数据库类型，目前支持 sqlite/mysql/mssql/postgres
Type = postgres
; MySQL 端口
Port = 
; 用户名
User = 
; 密码
Password = 
; 数据库地址
Host = 
; 数据库名称
Name = 
; 数据表前缀
TablePrefix = cd
; 字符集
Charset = utf8

**Comment by lyj0309** [comment]
能够初始化吗

**Comment by lyj0309** [comment]
我测试的没有问题，重新安装试试吧，可以去railway日志找找原因

**Comment by haorenew** [comment]
> 我测试的没有问题，重新安装试试吧，可以去railway日志找找原因
是cloudreve的bug……这个能部署到koyeb吗https://app.koyeb.com/？我的railway账号被封了

**Comment by lyj0309** [comment]
> > 我测试的没有问题，重新安装试试吧，可以去railway日志找找原因
> > 是cloudreve的bug……这个能部署到koyeb吗[https://app.koyeb.com/？我的railway账号被封了](https://app.koyeb.com/%EF%BC%9F%E6%88%91%E7%9A%84railway%E8%B4%A6%E5%8F%B7%E8%A2%AB%E5%B0%81%E4%BA%86)

我到时候看看，这个平台延时太高了，我推荐一些靠谱点的，比如fly.io ,或者 azure的应用程序，都有免费额度，而且都有香港，速度还是很快的

**Comment by haorenew** [comment]
好的哇，谢谢，我研究下fly.io和azure,我把E5续订的E5调用API续订服务放koyeble.
