### ISSUE TITLE
如何部署到azure

### ISSUE THREAD

**Issue by CAB233** [lyj0309/pan#2]
请问能够详细说说步骤吗

**Comment by lyj0309** [comment]
https://github.com/lyj0309/pan/blob/main/azure.md

**Comment by CAB233** [comment]
感谢，已经部署成功。那么连接数据库的话是要将数据库配置写入仓库的 config.ini 吗，请问能不能像 railway 那样在 secret 中写入从而保证安全

**Comment by lyj0309** [comment]
已经更新文档，设置`CONFIG_URL`环境变量就行

**Comment by CAB233** [comment]
如果在 Azure 设置使用 GitHub Action 持续部署，只能使用自己仓库的镜像，那么镜像该如何自定义
